import type { Project, Task, User, ProjectStatus, TaskStatus, TaskPriority } from '../types';

export const sampleUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'admin',
    department: 'Engineering',
    auid: '12345678',
    status: 'online',
    interests: ['Project Management', 'Team Leadership', 'System Architecture']
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'project_manager',
    department: 'Product',
    auid: '87654321',
    status: 'busy',
    interests: ['Product Strategy', 'User Experience', 'Agile Development']
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    role: 'employee',
    department: 'Engineering',
    auid: '11223344',
    status: 'online',
    interests: ['Frontend Development', 'React', 'UI/UX Design']
  },
  {
    id: '4',
    name: 'Alice Wilson',
    email: 'alice.wilson@example.com',
    role: 'employee',
    department: 'Design',
    auid: '44332211',
    status: 'offline',
    interests: ['Visual Design', 'Brand Identity', 'Creative Direction']
  }
];

export const sampleProjects: Project[] = [
  {
    id: 'project-1',
    name: 'Website Redesign',
    description: 'Complete redesign of the company website with modern UI/UX principles.',
    status: 'active' as ProjectStatus,
    owner: sampleUsers[0],
    members: [sampleUsers[0], sampleUsers[1], sampleUsers[2]],
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-04-15'),
    progress: 65,
    tasks: [],
    comments: [
      {
        id: 'comment-1',
        content: 'Great progress on the design phase! The wireframes look fantastic.',
        author: sampleUsers[1],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-15')
      },
      {
        id: 'comment-2',
        content: 'We need to finalize the color scheme before moving to development.',
        author: sampleUsers[0],
        createdAt: new Date('2024-02-18'),
        updatedAt: new Date('2024-02-18')
      }
    ],
    documents: [
      {
        id: 'doc-1',
        name: 'Design Guidelines.pdf',
        url: '/documents/design-guidelines.pdf',
        size: 2048576,
        type: 'application/pdf',
        uploadedBy: sampleUsers[1],
        uploadedAt: new Date('2024-02-10'),
        description: 'Brand guidelines and design system documentation'
      },
      {
        id: 'doc-2',
        name: 'Wireframes.fig',
        url: '/documents/wireframes.fig',
        size: 5242880,
        type: 'application/figma',
        uploadedBy: sampleUsers[2],
        uploadedAt: new Date('2024-02-12'),
        description: 'Figma wireframes for all pages'
      }
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-20'),
    color: '#3B82F6'
  },
  {
    id: 'project-2',
    name: 'Mobile App Development',
    description: 'Develop a cross-platform mobile application for our services.',
    status: 'active' as ProjectStatus,
    owner: sampleUsers[1],
    members: [sampleUsers[1], sampleUsers[2], sampleUsers[3]],
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-06-01'),
    progress: 30,
    tasks: [],
    comments: [
      {
        id: 'comment-3',
        content: 'React Native setup is complete. Ready to start development!',
        author: sampleUsers[2],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      }
    ],
    documents: [
      {
        id: 'doc-3',
        name: 'API Documentation.md',
        url: '/documents/api-docs.md',
        size: 1024000,
        type: 'text/markdown',
        uploadedBy: sampleUsers[1],
        uploadedAt: new Date('2024-02-03'),
        description: 'API endpoints and integration guide'
      }
    ],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-20'),
    color: '#10B981'
  },
  {
    id: 'project-3',
    name: 'Database Migration',
    description: 'Migrate legacy database to modern cloud infrastructure.',
    status: 'planning' as ProjectStatus,
    owner: sampleUsers[0],
    members: [sampleUsers[0], sampleUsers[3]],
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-05-01'),
    progress: 15,
    tasks: [],
    comments: [],
    documents: [],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-20'),
    color: '#F59E0B'
  }
];

export const sampleTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Design new homepage layout',
    description: 'Create wireframes and mockups for the new homepage design.',
    status: 'done' as TaskStatus,
    priority: 'high' as TaskPriority,
    assignee: sampleUsers[1],
    reporter: sampleUsers[0],
    projectId: 'project-1',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-02-01'),
    dueDate: new Date('2024-02-01'),
    estimatedHours: 16,
    tags: ['design', 'frontend'],
    comments: [],
    checklist: [
      {
        id: 'checklist-1-1',
        title: 'Research competitor homepages',
        description: 'Analyze top 10 competitor websites for design inspiration',
        completed: true,
        completedBy: sampleUsers[1],
        completedAt: new Date('2024-01-18'),
        assignee: sampleUsers[1],
        estimatedHours: 4,
        actualHours: 3.5,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-01-16'),
        updatedAt: new Date('2024-01-18')
      },
      {
        id: 'checklist-1-2',
        title: 'Create wireframes',
        description: 'Design low-fidelity wireframes for all homepage sections',
        completed: true,
        completedBy: sampleUsers[1],
        completedAt: new Date('2024-01-22'),
        assignee: sampleUsers[1],
        estimatedHours: 6,
        actualHours: 5.5,
        dependencies: ['checklist-1-1'],
        blockedBy: [],
        createdAt: new Date('2024-01-16'),
        updatedAt: new Date('2024-01-22')
      },
      {
        id: 'checklist-1-3',
        title: 'Design high-fidelity mockups',
        description: 'Create detailed visual designs with colors, typography, and spacing',
        completed: true,
        completedBy: sampleUsers[1],
        completedAt: new Date('2024-01-28'),
        assignee: sampleUsers[1],
        estimatedHours: 6,
        actualHours: 7,
        dependencies: ['checklist-1-2'],
        blockedBy: [],
        createdAt: new Date('2024-01-16'),
        updatedAt: new Date('2024-01-28')
      }
    ]
  },
  {
    id: 'task-2',
    title: 'Implement responsive navigation',
    description: 'Build responsive navigation component with mobile support.',
    status: 'in-progress' as TaskStatus,
    priority: 'medium' as TaskPriority,
    assignee: sampleUsers[2],
    reporter: sampleUsers[0],
    projectId: 'project-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-15'),
    dueDate: new Date('2024-02-25'),
    estimatedHours: 12,
    tags: ['frontend', 'react'],
    comments: [],
    checklist: [
      {
        id: 'checklist-2-1',
        title: 'Set up navigation component structure',
        description: 'Create basic navigation component with TypeScript interfaces',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-03'),
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: 2,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-03')
      },
      {
        id: 'checklist-2-2',
        title: 'Implement desktop navigation',
        description: 'Build horizontal navigation bar for desktop screens',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-08'),
        assignee: sampleUsers[2],
        estimatedHours: 4,
        actualHours: 4.5,
        dependencies: ['checklist-2-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-08')
      },
      {
        id: 'checklist-2-3',
        title: 'Add mobile hamburger menu',
        description: 'Implement collapsible navigation for mobile devices',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 3,
        actualHours: undefined,
        dependencies: ['checklist-2-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-2-4',
        title: 'Add responsive breakpoints',
        description: 'Implement CSS media queries for different screen sizes',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: ['checklist-2-3'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-2-5',
        title: 'Test navigation on all devices',
        description: 'Cross-browser and cross-device testing',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-2-4'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      }
    ]
  },
  {
    id: 'task-3',
    title: 'Set up development environment',
    description: 'Configure React Native development environment for iOS and Android.',
    status: 'done' as TaskStatus,
    priority: 'high' as TaskPriority,
    assignee: sampleUsers[2],
    reporter: sampleUsers[1],
    projectId: 'project-2',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-05'),
    dueDate: new Date('2024-02-05'),
    estimatedHours: 8,
    tags: ['setup', 'mobile'],
    comments: [],
    checklist: [
      {
        id: 'checklist-3-1',
        title: 'Install Node.js and npm',
        description: 'Set up Node.js version 18+ and npm package manager',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-01'),
        assignee: sampleUsers[2],
        estimatedHours: 0.5,
        actualHours: 0.5,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-3-2',
        title: 'Install React Native CLI',
        description: 'Install React Native command line interface globally',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-01'),
        assignee: sampleUsers[2],
        estimatedHours: 0.5,
        actualHours: 0.5,
        dependencies: ['checklist-3-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-3-3',
        title: 'Set up Android Studio',
        description: 'Install and configure Android Studio with SDK',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-02'),
        assignee: sampleUsers[2],
        estimatedHours: 3,
        actualHours: 3.5,
        dependencies: ['checklist-3-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-02')
      },
      {
        id: 'checklist-3-4',
        title: 'Set up Xcode for iOS',
        description: 'Install Xcode and configure iOS simulator',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-03'),
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: 2,
        dependencies: ['checklist-3-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-03')
      },
      {
        id: 'checklist-3-5',
        title: 'Create test project',
        description: 'Initialize new React Native project and test on both platforms',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-02-05'),
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: 1.5,
        dependencies: ['checklist-3-3', 'checklist-3-4'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-05')
      }
    ]
  },
  {
    id: 'task-4',
    title: 'Create authentication flow',
    description: 'Implement user authentication with login and registration.',
    status: 'todo' as TaskStatus,
    priority: 'high' as TaskPriority,
    assignee: sampleUsers[3],
    reporter: sampleUsers[1],
    projectId: 'project-2',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
    dueDate: new Date('2024-03-01'),
    estimatedHours: 20,
    tags: ['auth', 'backend'],
    comments: [],
    checklist: [
      {
        id: 'checklist-4-1',
        title: 'Design database schema',
        description: 'Create user table with email, password hash, and profile fields',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: undefined,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      },
      {
        id: 'checklist-4-2',
        title: 'Set up JWT authentication',
        description: 'Implement JWT token generation and validation',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 4,
        actualHours: undefined,
        dependencies: ['checklist-4-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      },
      {
        id: 'checklist-4-3',
        title: 'Create registration endpoint',
        description: 'Build API endpoint for user registration with validation',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: undefined,
        dependencies: ['checklist-4-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      },
      {
        id: 'checklist-4-4',
        title: 'Create login endpoint',
        description: 'Build API endpoint for user login with credential validation',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: undefined,
        dependencies: ['checklist-4-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      },
      {
        id: 'checklist-4-5',
        title: 'Implement password hashing',
        description: 'Add bcrypt for secure password hashing and verification',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: ['checklist-4-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      },
      {
        id: 'checklist-4-6',
        title: 'Add input validation',
        description: 'Implement email format and password strength validation',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: ['checklist-4-3', 'checklist-4-4'],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      },
      {
        id: 'checklist-4-7',
        title: 'Write unit tests',
        description: 'Create comprehensive tests for all authentication endpoints',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: undefined,
        dependencies: ['checklist-4-6'],
        blockedBy: [],
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-02-05')
      }
    ]
  },
  {
    id: 'task-5',
    title: 'Research database options',
    description: 'Compare different cloud database solutions for migration.',
    status: 'review' as TaskStatus,
    priority: 'medium' as TaskPriority,
    assignee: sampleUsers[3],
    reporter: sampleUsers[0],
    projectId: 'project-3',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-18'),
    dueDate: new Date('2024-02-28'),
    estimatedHours: 16,
    tags: ['research', 'database'],
    comments: [],
    checklist: [
      {
        id: 'checklist-5-1',
        title: 'Identify current database requirements',
        description: 'Document current data volume, query patterns, and performance needs',
        completed: true,
        completedBy: sampleUsers[3],
        completedAt: new Date('2024-02-16'),
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: 3,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-16')
      },
      {
        id: 'checklist-5-2',
        title: 'Research AWS RDS options',
        description: 'Evaluate PostgreSQL, MySQL, and Aurora options on AWS',
        completed: true,
        completedBy: sampleUsers[3],
        completedAt: new Date('2024-02-17'),
        assignee: sampleUsers[3],
        estimatedHours: 4,
        actualHours: 4.5,
        dependencies: ['checklist-5-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-17')
      },
      {
        id: 'checklist-5-3',
        title: 'Research Google Cloud SQL',
        description: 'Compare Google Cloud SQL with AWS RDS for our use case',
        completed: true,
        completedBy: sampleUsers[3],
        completedAt: new Date('2024-02-18'),
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: 2.5,
        dependencies: ['checklist-5-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-18')
      },
      {
        id: 'checklist-5-4',
        title: 'Research Azure Database',
        description: 'Evaluate Azure Database for PostgreSQL and MySQL',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 3,
        actualHours: undefined,
        dependencies: ['checklist-5-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-15')
      },
      {
        id: 'checklist-5-5',
        title: 'Create comparison matrix',
        description: 'Build detailed comparison of features, pricing, and performance',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: ['checklist-5-2', 'checklist-5-3', 'checklist-5-4'],
        blockedBy: [],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-15')
      },
      {
        id: 'checklist-5-6',
        title: 'Write recommendation report',
        description: 'Document final recommendation with migration plan',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-5-5'],
        blockedBy: [],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-02-15')
      }
    ]
  },
  {
    id: 'task-6',
    title: 'Fix header styling issues',
    description: 'Resolve CSS conflicts in the header component.',
    status: 'todo' as TaskStatus,
    priority: 'urgent' as TaskPriority,
    assignee: sampleUsers[2],
    reporter: sampleUsers[0],
    projectId: 'project-1',
    createdAt: new Date('2024-02-18'),
    updatedAt: new Date('2024-02-18'),
    dueDate: new Date('2024-02-22'),
    estimatedHours: 4,
    tags: ['bugfix', 'css'],
    comments: [],
    checklist: [
      {
        id: 'checklist-6-1',
        title: 'Identify CSS conflicts',
        description: 'Use browser dev tools to identify conflicting CSS rules',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-18'),
        updatedAt: new Date('2024-02-18')
      },
      {
        id: 'checklist-6-2',
        title: 'Fix z-index issues',
        description: 'Resolve overlapping elements and layering problems',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-6-1'],
        blockedBy: [],
        createdAt: new Date('2024-02-18'),
        updatedAt: new Date('2024-02-18')
      },
      {
        id: 'checklist-6-3',
        title: 'Fix responsive breakpoints',
        description: 'Ensure header displays correctly on all screen sizes',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-6-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-18'),
        updatedAt: new Date('2024-02-18')
      },
      {
        id: 'checklist-6-4',
        title: 'Test cross-browser compatibility',
        description: 'Verify fixes work in Chrome, Firefox, Safari, and Edge',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-6-3'],
        blockedBy: [],
        createdAt: new Date('2024-02-18'),
        updatedAt: new Date('2024-02-18')
      }
    ]
  },
  {
    id: 'task-7',
    title: 'Update API documentation',
    description: 'Update API documentation with new endpoints and examples.',
    status: 'in-progress' as TaskStatus,
    priority: 'medium' as TaskPriority,
    assignee: sampleUsers[2],
    reporter: sampleUsers[0],
    projectId: 'project-1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-25'),
    dueDate: new Date('2024-01-30'), // Overdue by several days
    estimatedHours: 8,
    tags: ['documentation', 'api'],
    comments: [],
    checklist: [
      {
        id: 'checklist-7-1',
        title: 'Audit existing API endpoints',
        description: 'Review all current API endpoints and identify missing documentation',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-01-22'),
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: 2.5,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-01-22')
      },
      {
        id: 'checklist-7-2',
        title: 'Document new authentication endpoints',
        description: 'Add documentation for login, register, and token refresh endpoints',
        completed: true,
        completedBy: sampleUsers[2],
        completedAt: new Date('2024-01-24'),
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: 2,
        dependencies: ['checklist-7-1'],
        blockedBy: [],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-01-24')
      },
      {
        id: 'checklist-7-3',
        title: 'Add request/response examples',
        description: 'Create detailed examples for all API endpoints',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: ['checklist-7-2'],
        blockedBy: [],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-01-20')
      },
      {
        id: 'checklist-7-4',
        title: 'Update error code documentation',
        description: 'Document all possible error responses and status codes',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-7-2'],
        blockedBy: [],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-01-20')
      },
      {
        id: 'checklist-7-5',
        title: 'Review and publish documentation',
        description: 'Final review and publish updated documentation',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[2],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-7-3', 'checklist-7-4'],
        blockedBy: [],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-01-20')
      }
    ]
  },
  {
    id: 'task-8',
    title: 'Performance optimization',
    description: 'Optimize database queries and improve application performance.',
    status: 'todo' as TaskStatus,
    priority: 'high' as TaskPriority,
    assignee: sampleUsers[3],
    reporter: sampleUsers[1],
    projectId: 'project-2',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    dueDate: new Date('2024-01-25'), // Overdue by many days
    estimatedHours: 24,
    tags: ['performance', 'optimization'],
    comments: [],
    checklist: [
      {
        id: 'checklist-8-1',
        title: 'Profile current performance',
        description: 'Run performance profiling to identify bottlenecks',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 4,
        actualHours: undefined,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15')
      },
      {
        id: 'checklist-8-2',
        title: 'Optimize database queries',
        description: 'Add indexes, optimize slow queries, and implement query caching',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 8,
        actualHours: undefined,
        dependencies: ['checklist-8-1'],
        blockedBy: [],
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15')
      },
      {
        id: 'checklist-8-3',
        title: 'Implement Redis caching',
        description: 'Add Redis for session and data caching',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 6,
        actualHours: undefined,
        dependencies: ['checklist-8-1'],
        blockedBy: [],
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15')
      },
      {
        id: 'checklist-8-4',
        title: 'Optimize frontend bundle',
        description: 'Implement code splitting and lazy loading',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 4,
        actualHours: undefined,
        dependencies: ['checklist-8-1'],
        blockedBy: [],
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15')
      },
      {
        id: 'checklist-8-5',
        title: 'Add performance monitoring',
        description: 'Implement APM tools and performance metrics',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[3],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: ['checklist-8-2', 'checklist-8-3', 'checklist-8-4'],
        blockedBy: [],
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15')
      }
    ]
  },
  {
    id: 'task-9',
    title: 'User testing session',
    description: 'Conduct user testing session for the new mobile app features.',
    status: 'todo' as TaskStatus,
    priority: 'medium' as TaskPriority,
    assignee: sampleUsers[1],
    reporter: sampleUsers[0],
    projectId: 'project-2',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    dueDate: new Date('2024-02-05'), // Recently overdue
    estimatedHours: 6,
    tags: ['testing', 'user-research'],
    comments: [],
    checklist: [
      {
        id: 'checklist-9-1',
        title: 'Recruit test participants',
        description: 'Find 8-10 users who match target demographic',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[1],
        estimatedHours: 2,
        actualHours: undefined,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-9-2',
        title: 'Prepare test scenarios',
        description: 'Create realistic user scenarios and test scripts',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[1],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: [],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-9-3',
        title: 'Set up testing environment',
        description: 'Prepare devices, recording equipment, and testing space',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[1],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-9-2'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-9-4',
        title: 'Conduct testing sessions',
        description: 'Run 1-hour testing sessions with each participant',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[1],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-9-1', 'checklist-9-3'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      },
      {
        id: 'checklist-9-5',
        title: 'Analyze results and create report',
        description: 'Compile findings and create actionable recommendations',
        completed: false,
        completedBy: undefined,
        completedAt: undefined,
        assignee: sampleUsers[1],
        estimatedHours: 1,
        actualHours: undefined,
        dependencies: ['checklist-9-4'],
        blockedBy: [],
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-02-01')
      }
    ]
  }
];
